language: r

warnings_are_errors: true

before_install:
   - sudo add-apt-repository -y "ppa:marutter/rrutter"
   - sudo add-apt-repository -y "ppa:marutter/c2d4u"
   - sudo apt-get update -qq
   - sudo apt-get install -y r-cran-ncdf

install: true
  
script: Rscript -e "source('new_funs/check.bio3d.R'); check.bio3d('ver_devel/bio3d')"

notifications:
  email:
    recipients:
       - bjgrant@umich.edu
       - xinqyao@umich.edu
       - larsss@gmail.com
    on_success: change
    on_failure: change
