# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:latest
pipelines:
#  default:
#      - step:
#              image: r-base
#              script:
#                        - apt-get update -qq
#                        - apt-get install libcurl4-openssl-dev libssl-dev libxml2-dev libnetcdf-dev qpdf texinfo texlive texlive-latex-extra texlive-fonts-extra
#                        - Rscript -e 'install.packages(c("rmarkdown", "devtools"))'
#                        - Rscript -e 'devtools::install_deps("ver_devel/bio3d", dependencies=TRUE)'
#                        - if test ! -d ~/.R; then mkdir ~/.R; fi
#                        - echo '_R_CHECK_CRAN_INCOMING_=FALSE' > ~/.R/check.Renviron
#                        - R CMD build ver_devel/bio3d && R CMD check --as-cran --run-donttest bio3d*.tar.gz && ! grep -q -e ERROR -e WARNING bio3d.Rcheck/00check.log
  branches:
    master:
      - step:
              script:
                        - echo "Syncronize master branch of bio3d repo at Bitbucket and Githup"
                        - git remote add github git@github.com:Grantlab/bio3d.git
                        - git push github master:master
    releases:
      - step:
              script:
                        - echo "Syncronize releases branch of bio3d repo at Bitbucket and Githup"
                        - if ! git remote -v | awk '{print $1}' | grep -q github; then git remote add github git@github.com:Grantlab/bio3d.git; fi
                        - git push github releases:releases
                        
    # temporary test (to be deleted after merging into master)
    bugfix_readpdb:
      - step:
              deployment: test
              script:
                        - echo "Syncronize bugfix_readpdb branch of bio3d repo at Bitbucket and Githup"
                        - if ! git remote -v | awk '{print $1}' | grep -q github; then git remote add github git@github.com:Grantlab/bio3d.git; fi
                        - git push github bugfix_readpdb:bugfix_readpdb
